-- 1
ALTER SESSION SET "_oracle_script" = TRUE;

CREATE USER lab9user IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_VDI
TEMPORARY TABLESPACE TS_VDI_TEMP
ACCOUNT UNLOCK

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE TO lab9user;
GRANT CREATE SEQUENCE TO lab9user;
GRANT CREATE CLUSTER TO lab9user;
GRANT CREATE SYNONYM TO lab9user;
GRANT CREATE PUBLIC SYNONYM TO lab9user;
GRANT CREATE MATERIALIZED VIEW TO lab9user;

ALTER USER lab9user QUOTA UNLIMITED ON TS_VDI;

-- 2

CREATE GLOBAL TEMPORARY TABLE TEMP_TABLE (
    ID INT,
    NAME NVARCHAR2(30)
);

BEGIN
    FOR i IN 1..20 
    LOOP
        INSERT INTO TEMP_TABLE(ID, NAME) VALUES (i, TO_CHAR(i));
    END LOOP;
END;

SELECT * FROM TEMP_TABLE;

COMMIT;

-- 3

CREATE SEQUENCE S1
    START WITH 1000
    INCREMENT BY 10
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    NOCACHE
    NOORDER;

SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.CURRVAL FROM DUAL;
DROP SEQUENCE S1;

-- 4

CREATE SEQUENCE S2
    START WITH 10
    INCREMENT BY 10
    MAXVALUE 100
    NOCYCLE;

SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.CURRVAL FROM DUAL;
DROP SEQUENCE S2;

-- 5

CREATE SEQUENCE S3
    START WITH 10
    INCREMENT BY -10
    MINVALUE -100
    MAXVALUE 10
    NOCYCLE
    ORDER;

SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.CURRVAL FROM DUAL;
DROP SEQUENCE S3;

-- 6

CREATE SEQUENCE S4
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 10
    CYCLE
    CACHE 5
    NOORDER;

SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.CURRVAL FROM DUAL;
DROP SEQUENCE S4;

-- 7

SELECT * FROM USER_SEQUENCES;

-- 8

CREATE TABLE T1 (
    N1 NUMBER(20),
    N2 NUMBER(20),
    N3 NUMBER(20),
    N4 NUMBER(20)
)
CACHE STORAGE (BUFFER_POOL KEEP);

BEGIN
    FOR i IN 1..7
    LOOP
        INSERT INTO T1(N1, N2, N3, N4) VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
    END LOOP;
END;

SELECT * FROM T1;

-- 9

CREATE CLUSTER ABC (
    X NUMBER(10),
    V VARCHAR(12)
)
hashkeys 200;

-- 10

CREATE TABLE A (
    XA NUMBER(10),
    VA VARCHAR(12),
    NA NUMBER(15)
)
CLUSTER ABC(XA, VA);

-- 11

CREATE TABLE B (
    XB NUMBER(10),
    VB VARCHAR(12),
    NB NUMBER(15)
)
CLUSTER ABC(XB, VB);

-- 12

CREATE TABLE C (
    XC NUMBER(10),
    VC VARCHAR(12),
    NC NUMBER(15)
)
CLUSTER ABC(XC, VC);

-- 13

SELECT * FROM USER_CLUSTERS;
SELECT * FROM USER_TABLES;

-- 14

-- от лица lab9user
INSERT INTO C VALUES (1, '1', 1) ;
CREATE SYNONYM CTABLE FOR C;
GRANT SELECT ON CTABLE TO system;

SELECT * FROM CTABLE;
SELECT * FROM C;

-- от лица system
SELECT * FROM CTABLE;
SELECT * FROM C;
SELECT * FROM lab9user.C;

-- 15
-- от лица lab9user
CREATE PUBLIC SYNONYM BTABLE FOR B;
GRANT SELECT ON BTABLE TO system;
INSERT INTO BTABLE VALUES (1, '1', 1) ;
SELECT * FROM BTABLE;
SELECT * FROM B;

-- от лица system
SELECT * FROM BTABLE;
SELECT * FROM B;
SELECT * FROM lab9user.B;

-- 16

CREATE TABLE D (
    ID INT PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE E (
    ID INT REFERENCES D(ID),
    NAME VARCHAR(20)
);

BEGIN
    FOR i IN 1..100
    LOOP
        INSERT INTO D(ID, NAME) VALUES (i, CONCAT('TABLE D', TO_CHAR(i)));
        INSERT INTO E(ID, NAME) VALUES (i, CONCAT('TABLE E', TO_CHAR(i)));
    END LOOP;
END;

SELECT * FROM E;
SELECT * FROM D;

CREATE VIEW V1 AS
    SELECT D.ID, D.NAME AS DNAME, E.NAME AS ENAME
    FROM D INNER JOIN E ON D.ID = E.ID;

SELECT * FROM V1;

-- 17

CREATE MATERIALIZED VIEW MV_VDI
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
START WITH SYSDATE
NEXT SYSDATE + INTERVAL '2' MINUTE
AS
    SELECT D.ID, D.NAME AS DNAME, E.NAME AS ENAME
    FROM D INNER JOIN E ON D.ID = E.ID;

SELECT * FROM MV_VDI;

INSERT INTO D(ID, NAME) VALUES (103, CONCAT('TABLE D', TO_CHAR(103)));
INSERT INTO E(ID, NAME) VALUES (103, CONCAT('TABLE E', TO_CHAR(103)));
COMMIT;

DROP MATERIALIZED VIEW MV_VDI;

-- 18 НАДО ТЕСТИТЬ С ЮЛИАННОЙ

GRANT CREATE DATABASE LINK TO lab9user;

CREATE DATABASE LINK TVOYFAVV_DB
CONNECT TO C##KROU4
IDENTIFIED BY "12345"
USING 'TVOYFAVVPDB';

SELECT * FROM countries@TVOYFAVV_DB;
INSERT INTO countries@TVOYFAVV_DB (id, country_name) VALUES (5, 'Беларусь');
COMMIT;
UPDATE countries@TVOYFAVV_DB SET country_name='Япония' WHERE id=5;
COMMIT;
DELETE FROM countries@TVOYFAVV_DB WHERE id=5;
COMMIT;
