set serveroutput on;

-- 1 -- преподаватели заданной кафедры
DECLARE
    PROCEDURE GET_TEACHERS(
        PCODE TEACHER.PULPIT%TYPE
    )
    IS
        CURSOR TEACHERS_CURSOR IS SELECT * FROM TEACHER WHERE PULPIT = PCODE;
        TEACHER_REC TEACHER%ROWTYPE;
    BEGIN
        FOR TEACHER_REC IN TEACHERS_CURSOR LOOP
            DBMS_OUTPUT.PUT_LINE(
                TEACHERS_CURSOR%ROWCOUNT ||  '. ' ||  TEACHER_REC.PULPIT ||  ' ' ||  TEACHER_REC.TEACHER ||  ' ' ||  TEACHER_REC.TEACHER_NAME);
        END LOOP;
    END;
BEGIN
    GET_TEACHERS('ISiT');
END;

-- 2 -- колво преподавателей кафедры

DECLARE
    FUNCTION GET_NUM_TEACHERS(
        PCODE TEACHER.PULPIT%TYPE
    )
    RETURN NUMBER
    IS
        NUM_TEACHERS NUMBER;
    BEGIN
        SELECT COUNT(*) INTO NUM_TEACHERS FROM TEACHER WHERE PULPIT = PCODE;
        RETURN NUM_TEACHERS;
    END;
BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_NUM_TEACHERS('ISiT'));
END;

-- 3 

CREATE OR REPLACE PROCEDURE GET_TEACHERS( -- преподаватели факультета
    FCODE FACULTY.FACULTY%TYPE
)
IS
    CURSOR TEACHERS_CURSOR IS SELECT TEACHER, TEACHER_NAME, PULPIT.PULPIT, PULPIT.FACULTY
        FROM TEACHER 
        INNER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT
        WHERE FACULTY = FCODE;
    TEACHER_REC TEACHER%ROWTYPE;
BEGIN
    FOR TEACHER_REC IN TEACHERS_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE(TEACHERS_CURSOR%ROWCOUNT ||  '. ' ||  TEACHER_REC.FACULTY ||  ' ' ||  TEACHER_REC.PULPIT
        ||  ' ' ||  TEACHER_REC.TEACHER ||  ' ' ||  TEACHER_REC.TEACHER_NAME);
    END LOOP;
END;

BEGIN
    GET_TEACHERS('IDiP');
END;



CREATE OR REPLACE PROCEDURE GET_SUBJECTS( -- дисциплины кафедры
    PCODE SUBJECT.PULPIT%TYPE
)
IS
    CURSOR SUBJECTS_CURSOR IS SELECT * FROM SUBJECT WHERE PULPIT = PCODE;
    SUBJECT_REC SUBJECT%ROWTYPE;
BEGIN
    FOR SUBJECT_REC IN SUBJECTS_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE(SUBJECTS_CURSOR%ROWCOUNT ||  '. ' ||  SUBJECT_REC.PULPIT ||  ' '
        ||  SUBJECT_REC.SUBJECT ||  ' ' ||  SUBJECT_REC.SUBJECT_NAME);
    END LOOP;
END;

BEGIN
    GET_SUBJECTS('ISiT');
END;

--- 4

CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS( -- колво преподавателей факультета
    FCODE FACULTY.FACULTY%TYPE
)
RETURN NUMBER
IS
    NUM_TEACHERS NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM_TEACHERS FROM TEACHER
        INNER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT
        WHERE FACULTY = FCODE;
    RETURN NUM_TEACHERS;
END;


BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_NUM_TEACHERS('IDiP'));
END;


CREATE OR REPLACE FUNCTION GET_NUM_SUBJECTS( -- колво дисциплин кафедры
    PCODE SUBJECT.PULPIT%TYPE
)
RETURN NUMBER
IS
    NUM_SUBJECTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM_SUBJECTS FROM SUBJECT WHERE PULPIT = PCODE;
    RETURN NUM_SUBJECTS;
END;


BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_NUM_SUBJECTS('ISiT'));
END;

-- 5

CREATE OR REPLACE PACKAGE TEACHERS IS
    PROCEDURE GET_TEACHERS(FCODE FACULTY.FACULTY%TYPE);
    PROCEDURE GET_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE);
    FUNCTION GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER;
    FUNCTION GET_NUM_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END;

CREATE OR REPLACE PACKAGE BODY TEACHERS IS

    PROCEDURE GET_TEACHERS( -- преподаватели факультета
        FCODE FACULTY.FACULTY%TYPE
    )
    IS
        CURSOR TEACHERS_CURSOR IS SELECT TEACHER, TEACHER_NAME, PULPIT.PULPIT, PULPIT.FACULTY
            FROM TEACHER 
            INNER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT
            WHERE FACULTY = FCODE;
        TEACHER_REC TEACHER%ROWTYPE;
    BEGIN
        FOR TEACHER_REC IN TEACHERS_CURSOR LOOP
            DBMS_OUTPUT.PUT_LINE(TEACHERS_CURSOR%ROWCOUNT ||  '. ' ||  TEACHER_REC.FACULTY ||  ' ' ||  TEACHER_REC.PULPIT
            ||  ' ' ||  TEACHER_REC.TEACHER ||  ' ' ||  TEACHER_REC.TEACHER_NAME);
        END LOOP;
    END;

    
    PROCEDURE GET_SUBJECTS( -- дисциплины кафедры
        PCODE SUBJECT.PULPIT%TYPE
    )
    IS
        CURSOR SUBJECTS_CURSOR IS SELECT * FROM SUBJECT WHERE PULPIT = PCODE;
        SUBJECT_REC SUBJECT%ROWTYPE;
    BEGIN
        FOR SUBJECT_REC IN SUBJECTS_CURSOR LOOP
            DBMS_OUTPUT.PUT_LINE(SUBJECTS_CURSOR%ROWCOUNT ||  '. ' ||  SUBJECT_REC.PULPIT ||  ' '
            ||  SUBJECT_REC.SUBJECT ||  ' ' ||  SUBJECT_REC.SUBJECT_NAME);
        END LOOP;
    END;


    FUNCTION GET_NUM_TEACHERS( -- колво преподавателей факультета
        FCODE FACULTY.FACULTY%TYPE
    )
    RETURN NUMBER
    IS
        NUM_TEACHERS NUMBER;
    BEGIN
        SELECT COUNT(*) INTO NUM_TEACHERS FROM TEACHER
            INNER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT
            WHERE FACULTY = FCODE;
        RETURN NUM_TEACHERS;
    END;

    
    FUNCTION GET_NUM_SUBJECTS( -- колво дисциплин кафедры
        PCODE SUBJECT.PULPIT%TYPE
    )
    RETURN NUMBER
    IS
        NUM_SUBJECTS NUMBER;
    BEGIN
        SELECT COUNT(*) INTO NUM_SUBJECTS FROM SUBJECT WHERE PULPIT = PCODE;
        RETURN NUM_SUBJECTS;
    END;
    
END;

-- 6

BEGIN
    TEACHERS.GET_TEACHERS('IDiP');
    TEACHERS.GET_SUBJECTS('ISiT');
    DBMS_OUTPUT.PUT_LINE(TEACHERS.GET_NUM_TEACHERS('IDiP'));
    DBMS_OUTPUT.PUT_LINE(TEACHERS.GET_NUM_SUBJECTS('ISiT'));
END;